testing pre-commit hook

diff --git a/scripts/gitHooks/pre-commit b/scripts/gitHooks/pre-commit
--- a/scripts/gitHooks/pre-commit
+++ b/scripts/gitHooks/pre-commit
@@ -9,7 +9,19 @@ then
   echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
   echo "    Linter looks good"
   echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
-  exit 0
+  npm test
+  if [ $? -eq 0 ]
+  then
+      echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
+      echo "    Tets looks good"
+      echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
+      exit 0
+  else
+    echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
+    echo "  Sorry bro, you'll have to check the test failing above" >&2
+    echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
+    exit 1
+  fi
 else
 
   echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
