fix babel jest config using react-native-elements config

diff --git a/scripts/gitHooks/pre-commit b/scripts/gitHooks/pre-commit
--- a/scripts/gitHooks/pre-commit
+++ b/scripts/gitHooks/pre-commit
@@ -13,19 +13,19 @@ then
   if [ $? -eq 0 ]
   then
       echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
-      echo "    Tets looks good"
+      echo "    Tests looks good"
       echo "✨✨✨✨✨✨✨✨✨✨✨✨✨"
       exit 0
   else
-    echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
-    echo "  Sorry bro, you'll have to check the test failing above" >&2
-    echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
+    echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
+    echo " Sorry bro, you'll have to check the failing tests above in order to commit that code" >&2
+    echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
     exit 1
   fi
 else
 
   echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
-  echo "  Sorry bro, you'll have to check the linter errros above" >&2
+  echo " Sorry bro, you'll have to check the linter errros above" >&2
   echo "💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥💥" >&2
   exit 1
 fi
